runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /home
  script: main.app
  login: required
  auth_fail_action: redirect

- url: /people
  script: main.app
  login: required
  auth_fail_action: redirect

- url: /form
  script: main.app
  login: required
  auth_fail_action: redirect

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
